src/main/webapp/help-srcLocation.html
=> [D-324012] Updating verbiage on help message for source location text box

src/main/java/org/jenkinsci/plugins/fodupload/ApiConnectionFactory.java, src/main/java/org/jenkinsci/plugins/fodupload/FodApiConnection.java, src/main/java/org/jenkinsci/plugins/fodupload/FodGlobalDescriptor.java, src/main/java/org/jenkinsci/plugins/fodupload/PollingBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/SharedPollingBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/SharedUploadBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/StaticAssessmentBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/Utils.java, src/main/java/org/jenkinsci/plugins/fodupload/controllers/ReleaseController.java, src/main/java/org/jenkinsci/plugins/fodupload/controllers/StaticScanController.java, src/main/java/org/jenkinsci/plugins/fodupload/controllers/StaticScanSummaryController.java, src/main/java/org/jenkinsci/plugins/fodupload/models/AuthenticationModel.java, src/main/java/org/jenkinsci/plugins/fodupload/models/FodEnums.java, src/main/java/org/jenkinsci/plugins/fodupload/models/JobModel.java, src/main/java/org/jenkinsci/plugins/fodupload/models/response/LookupItemsModel.java, src/main/java/org/jenkinsci/plugins/fodupload/polling/ScanStatusPoller.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyPollResults.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyStaticAssessment.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyStep.java
Reformatting files using intellij reformatting.
=> Reformatting files

pom.xml, src/main/java/org/jenkinsci/plugins/fodupload/ApiConnectionFactory.java, src/main/java/org/jenkinsci/plugins/fodupload/FodGlobalDescriptor.java, src/main/java/org/jenkinsci/plugins/fodupload/PollingBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/SharedPollingBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/SharedUploadBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/StaticAssessmentBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/Utils.java, src/main/java/org/jenkinsci/plugins/fodupload/controllers/StaticScanController.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyPollResults.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyStaticAssessment.java, src/main/resources/org/jenkinsci/plugins/fodupload/FodGlobalDescriptor/config.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/PollingBuildStep/config.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/StaticAssessmentBuildStep/config.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyPollResults/config.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyStaticAssessment/config.jelly
Adding credentials to both pipeline and freestyle projects. 
Removing decryption logic in favor of just passing ids.
=> [US-331023][US-331022] Adding credentials to both pipeline and freestyle projects. Removing decryption logic in favor of just passing ids.

pom.xml, src/main/java/org/jenkinsci/plugins/fodupload/ApiConnectionFactory.java, src/main/java/org/jenkinsci/plugins/fodupload/FodGlobalDescriptor.java, src/main/java/org/jenkinsci/plugins/fodupload/PollingBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/SharedPollingBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/SharedUploadBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/StaticAssessmentBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/Utils.java, src/main/java/org/jenkinsci/plugins/fodupload/controllers/StaticScanController.java, src/main/java/org/jenkinsci/plugins/fodupload/models/FodEnums.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyPollResults.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyStaticAssessment.java, src/main/resources/org/jenkinsci/plugins/fodupload/FodGlobalDescriptor/config.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/PollingBuildStep/config.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/StaticAssessmentBuildStep/config.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyPollResults/config.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyStaticAssessment/config.jelly
**THIS IS THE PR 2/2**
**PR 1/2: https://github.com/fod-dev/fortify-on-demand-uploader-plugin/pull/29 ** 
- Updating all dropdowns to use friendly names. Updating Enums to use strings instead of Integers as default index values.
- Updating InProgresScanAction dropdown box to use Enum.
=> US-327011-V Updating remaining drop downs to use enums

CHANGELOG.md, src/main/java/org/jenkinsci/plugins/fodupload/SharedPollingBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/SharedUploadBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyPollResults.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyStaticAssessment.java
https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=344001
=> [D-344001] Protect all doTestPersonalAccessTokenConnection methods

src/main/java/org/jenkinsci/plugins/fodupload/SharedPollingBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/SharedUploadBuildStep.java
When both release id and BSI token are provided, we write a warning
=> [D-372010] add warning on both releaseId and bsi token

README.md
=> Update Link to Wiki

src/main/java/org/jenkinsci/plugins/fodupload/StaticAssessmentBuildStep.java
[D-418012] Fixed a typo that prevented settings from populating in the freestyle project configuration menu
=> [D-418012] Fixed a typo that prevented settings from populating in the freestyle project configuration menu

src/main/java/org/jenkinsci/plugins/fodupload/controllers/AssessmentTypesController.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyStaticAssessment.java, src/main/webapp/PipelineGenerator.js, src/main/webapp/ScanSettings.js
D-557013 Account for microservice for autoprov assessments
D-560003 Fix for losing SC selection in pipeline
=> [D-557013] & [D-560003]

src/main/java/org/jenkinsci/plugins/fodupload/Utils.java, src/main/java/org/jenkinsci/plugins/fodupload/models/response/PollingSummaryDTO.java, src/main/java/org/jenkinsci/plugins/fodupload/polling/ScanStatusPoller.java
This was done by @aishkotni 
[D-602004](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=602004)
=> [D-602004] kotlin files not included in java payload

CHANGELOG.md
Added support for Jenkins Configuration as Code.
Added support for Fortify On Demand URL validation.
Fixed issue where Kotlin files were not being packaged.
=> Release 7.1.1

CHANGELOG.md
[D-746008] Security Vulnerability - Commons Text Library needs to be upgraded to a minimum version of 1.10
=> [D-746008] Security Vulnerability - Commons Text Library needs to be upgraded to a minimum version of 1.10

CHANGELOG.md
=> Updated changelog for 7.2

src/main/resources/org/jenkinsci/plugins/fodupload/DastFreeStyleBuildStep/ScanSettings.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/DastFreeStyleBuildStep/config.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipelineAssessment/config.jelly, src/main/webapp/DastPipelineGenerator.js, src/main/webapp/DastScanSettings.js, src/main/webapp/DastValidation.js
[T-502002](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=task&id=502002) [T-505003](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=task&id=505003)
=> [T-502002][T-505003] Added validation for Dast Pipeline and spinner for Release Id change

src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline/config.jelly, src/main/webapp/DastValidation.js
[T-502002](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=task&id=502002)
=> [T-502002] Added file extension validation for all Dast API type File Path.

src/main/java/org/jenkinsci/plugins/fodupload/Config/FodGlobalConstants.java, src/main/java/org/jenkinsci/plugins/fodupload/DastScanSharedBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/FortifyDastFreeStyleBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/models/DastScanJobModel.java, src/main/java/org/jenkinsci/plugins/fodupload/models/LoginMacroFileCreationDetails.java, src/main/java/org/jenkinsci/plugins/fodupload/models/PutDastScanSetupReqModel.java, src/main/java/org/jenkinsci/plugins/fodupload/models/PutDastWebSiteScanReqModel.java, src/main/java/org/jenkinsci/plugins/fodupload/models/response/Dast/GetDastScanSettingResponse.java, src/main/java/org/jenkinsci/plugins/fodupload/models/response/PatchDastFileUploadResponse.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline.java, src/main/resources/org/jenkinsci/plugins/fodupload/FortifyDastFreeStyleBuildStep/ScanSettings.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline/config.jelly, src/main/webapp/Api.js, src/main/webapp/AppAndReleaseSelection.js, src/main/webapp/DastFreeStyle.js, src/main/webapp/DastPipelineGenerator.js
Retrival of fields related to additiona services need to fix
=> Addition features for FOD

src/main/java/org/jenkinsci/plugins/fodupload/DastScanSharedBuildStep.java, src/main/resources/org/jenkinsci/plugins/fodupload/FortifyDastFreeStyleBuildStep/ScanSettings.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/FortifyDastFreeStyleBuildStep/config.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline/config.jelly, src/main/webapp/DastFreeStyle.js, src/main/webapp/DastPipelineGenerator.js, src/main/webapp/DastValidation.js
[US-1477008](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1477008) / [T-514001](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=task&id=514001)
=> [US-147008]/T[514001] Added Validations for DAST Pipeline and Dast Freestyle

src/main/java/org/jenkinsci/plugins/fodupload/DastScanSharedBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/FortifyDastFreeStyleBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/models/FodEnums.java, src/main/java/org/jenkinsci/plugins/fodupload/models/PutDastWebSiteScanReqModel.java, src/main/java/org/jenkinsci/plugins/fodupload/models/response/Dast/ExcludedUrl.java, src/main/java/org/jenkinsci/plugins/fodupload/models/response/Dast/GetDastScanSettingResponse.java, src/main/java/org/jenkinsci/plugins/fodupload/models/response/Dast/Website.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline.java, src/main/resources/org/jenkinsci/plugins/fodupload/FortifyDastFreeStyleBuildStep/ScanSettings.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/FortifyDastFreeStyleBuildStep/config.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline/config.jelly, src/main/webapp/AppAndReleaseSelection.js, src/main/webapp/DastFreeStyle.js, src/main/webapp/DastPipelineGenerator.js, src/main/webapp/DastValidation.js
Defect Fixes for 
https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1600001 https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1597005 https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1600002 https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1598003 https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1602001 https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1603006 https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1606012 …
=> [DASTSupport] Defect fixes for

src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline.java, src/main/resources/org/jenkinsci/plugins/fodupload/FortifyDastFreeStyleBuildStep/ScanSettings.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline/config.jelly, src/main/webapp/DastFreeStyle.js, src/main/webapp/DastPipelineGenerator.js, src/main/webapp/DastValidation.js
[D-1601001](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1601001)
[D-1599007](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1599007)
[D-1597016](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1597016)
[D-1599014](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1599014)
[D-1612008](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1612008)
[D-1612024](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1612024)
=> UI fixes for Jenkins freestyle and pipeline.

src/main/java/org/jenkinsci/plugins/fodupload/models/response/Dast/GetDastScanSettingResponse.java, src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline/config.jelly, src/main/webapp/DastFreeStyle.js, src/main/webapp/DastPipelineGenerator.js
Defect fix for 1600002,1597005 ,1610011,1606006
https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1600002 https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1597005 https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1610011
https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1606006
=> [DAST Support] Fix for

src/main/java/org/jenkinsci/plugins/fodupload/DastScanSharedBuildStep.java, src/main/resources/org/jenkinsci/plugins/fodupload/FortifyDastFreeStyleBuildStep/ScanSettings.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline/config.jelly, src/main/webapp/DastFreeStyle.js, src/main/webapp/DastPipelineGenerator.js
[D-1598002](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1598002) and fixed display issues.
=> [D-1598002] Fixed website scan scope restriction issue.

src/main/java/org/jenkinsci/plugins/fodupload/DastScanSharedBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/FortifyDastFreeStyleBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/models/PutDastAutomatedGraphQlReqModel.java, src/main/java/org/jenkinsci/plugins/fodupload/models/PutDastAutomatedGrpcReqModel.java, src/main/java/org/jenkinsci/plugins/fodupload/models/PutDastAutomatedOpenApiReqModel.java, src/main/java/org/jenkinsci/plugins/fodupload/models/PutDastAutomatedPostmanReqModel.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline.java
[D-1601013](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1601013)
=> [D-1601013] Fixed issue for Timebox value in API Scan Type.

src/main/java/org/jenkinsci/plugins/fodupload/controllers/DastScanController.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline.java
[D-1621018](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1621018)
=> [D-1621018] Resolved issue of creating new release for existing application

src/main/webapp/DastPipelineGenerator.js
[D-1622018](https://almoctane-ams.saas.microfocus.com/ui/entity-navigation?p=112082/7001&entityType=work_item&id=1622018)
=> [D-1622018]  Fixed issue for 'Assign to Me' function not capturing ownerId when perform Generate pipeline script.

src/main/webapp/Common.js, src/main/webapp/Styling.js
[DAST Support] Fix for spinner and Dialog window not working because of $ not recognized in latest version of Jenkin.
=>  [DAST Support] Fix for spinner and Dialog window not working because of $ not recognized in latest version of Jenkin.

CHANGELOG.md, README.md
Yeu-Li's changes from her fork manually applied to branch
=> 8.0 doc updates-limitations

src/main/resources/org/jenkinsci/plugins/fodupload/FortifyDastFreeStyleBuildStep/ScanSettings.jelly, src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline/config.jelly
[DAST Support] Fix for unit test failure while mvm publish.
=> [DAST Support] Fix for unit test failure while mvm publish.

pom.xml, src/main/java/org/jenkinsci/plugins/fodupload/DastScanSharedBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/FodApi/DastScanPayloadUpload.java, src/main/java/org/jenkinsci/plugins/fodupload/FortifyDastFreeStyleBuildStep.java, src/main/java/org/jenkinsci/plugins/fodupload/controllers/DastScanController.java, src/main/java/org/jenkinsci/plugins/fodupload/models/DastScanJobModel.java, src/main/java/org/jenkinsci/plugins/fodupload/models/ExclusionDTO.java, src/main/java/org/jenkinsci/plugins/fodupload/models/FodEnums.java, src/main/java/org/jenkinsci/plugins/fodupload/models/LoginMacroFileCreationDetails.java, src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline.java
Spot Bug Fixes - PR to merging into  (https://github.com/fod-dev/fortify-on-demand-uploader-plugin)/ Master. 
and Spotbug plugin addition into pom.xml file.
=> Spot Bug Fixes - PR to merging into  (https://github.com/fod-dev/fortify-on-demand-uploader-plugin)/ Master.

src/main/java/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline.java, src/main/resources/org/jenkinsci/plugins/fodupload/steps/FortifyDastPipeline/config.jelly
[DAST Support] Fix for (Website scan) Excluded URLs  field are not applied 8.0
=> [DAST Support] Fix for (Website scan) Excluded URLs are not applied 8.0
